### ISSUE TITLE
Remove eag attribute.

### ISSUE THREAD

**Issue by ZogopZ** [ICOS-Carbon-Portal/pylib#109]
Ute's comments

> The ‘eag’ (= elevation above ground level, see comments in the code) attribute doesn’t make sense anymore. 
It is set to the same values as ‘eas’ (=elevation above sea level) - which is complete nonsense. As long as the eag information was coming from the labelling app, it was at least not wrong. eag should simply be removed from the list of attributes in the next version.

- [x] Remove the `eag` attribute.
- [x] Find any associations of the attribute with other components of the `pylib` and adjust them accordingly.

**Comment by ukarst** [comment]
For backward compatibility, we should keep the eag attribute but set it to NaN.

**Comment by claudiodonofrio** [comment]
I am still not sure about this issue. My opinion is as follow:
keeping the attribute 'eag' and always set it to NaN does not make sense, then I propose removing the attribute.
In general, however, I think this is metadata we should provide. The naming is maybe not be the best, but initially this information was equivalent to the tower height.

**Comment by ukarst** [comment]
Minimum requirement: not set `eag` to the same value as `eas`
