### ISSUE TITLE
error creating a map with all stations

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/pylib#146]
from icoscp.station import station
station.getIdList(project='all', outfmt='map')

produces:
File /opt/conda/lib/python3.10/site-packages/icoscp/station/fmap.py:250, in edit_queried_stations(queried_stations, edited_response)
    248 station_info['country_code'] = station_info.pop('country')
    249 station_info['station_name'] = station_info.pop('name')
--> 250 station_info['country'] = countries_data[station_info.country_code]['name']
    251 station_info['flag'] = countries_data[station_info.country_code]['flag']
    252 stations.append(station_info)
KeyError: None

**Comment by ZogopZ** [comment]
There is no error coming up as of icoscp-0.2.1. This was probably addressed, somehow.
