### ISSUE TITLE
Dobj.latest

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/pylib#155]
The library contains two properties to check for previous and next version for the dataset
```
Dobj.previous
Dobj.next
```
It would be nice to use the existing information in the metadata 
dob.meta['latestVersion'] as a property, like Dobj.latest
for 'latest', such that the user always can load the newest, latest version of the dataset.

**Comment by ZogopZ** [comment]
Closed via [f12ec20](https://github.com/ICOS-Carbon-Portal/pylib/commit/f12ec20).
