### ISSUE TITLE
Rework the default return of `get_ts` in stiltobj.py

### ISSUE THREAD

**Issue by altix** [ICOS-Carbon-Portal/pylib#68]
Today the default return is ["isodate","co2.stilt","co2.fuel","co2.bio", "co2.background"]
it would be nice if we had ["isodate","co2.stilt","co2.fuel","co2.bio", "co2.cement", "co2.background"]
instead since then these are the components of co2.stilt:  
           co2.stilt = co2.fuel + co2.bio + co2.cement + co2.background

**Comment by ZogopZ** [comment]
Closed via #75
