### ISSUE TITLE
Update `get_ts` in stiltobj.py with new components.

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/pylib#70]
The spilt of co2 and co into components is updated in stiltweb. This makes a corresponding update in stiltobj.py get_ts necessary.

This issue is connected to https://github.com/ICOS-Carbon-Portal/pylib/issues/68 and https://github.com/ICOS-Carbon-Portal/pylib/issues/62

The new components and the order of the components is listed here:
[pylib_stilt_order.txt](https://github.com/ICOS-Carbon-Portal/pylib/files/8540455/pylib_stilt_order.txt)

**Comment by ZogopZ** [comment]
Closed via #75
